version: '3.8'

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    links:
      - php-fpm
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php-fpm
      - mysql

  php-fpm:
    build: php-fpm/
    container_name: php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./web:/var/www/html
      - ./web:/usr/share/nginx/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_ROOT_PASSWORD: root
  
  phpmyadmin:
    image: phpmyadmin
    container_name: php-my-admin
    ports:
      - 1500:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  nginx: 